// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-funnels.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var OWNER_EMAIL = "estevaopbxs@gmail.com";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function assertOwner(ctx) {
  if (!ctx.isAuthenticated()) return { ok: false, msg: "Not authenticated" };
  const email = (ctx.getUserEmail() ?? "").toLowerCase();
  if (email !== OWNER_EMAIL) return { ok: false, msg: "Not authorized" };
  return { ok: true };
}
var list_funnels_default = defineTool({
  name: "list_funnels",
  title: "List funnels",
  description: "List all conversion funnels saved by the owner.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const guard = assertOwner(ctx);
    if (!guard.ok) return { content: [{ type: "text", text: guard.msg }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("funnels").select("id,title,description,updated_at,created_at").order("updated_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { funnels: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-funnel.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var OWNER_EMAIL2 = "estevaopbxs@gmail.com";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_funnel_default = defineTool2({
  name: "get_funnel",
  title: "Get funnel",
  description: "Fetch a single funnel by id, including its nodes and edges.",
  inputSchema: { id: z.string().describe("Funnel UUID") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated() || (ctx.getUserEmail() ?? "").toLowerCase() !== OWNER_EMAIL2) {
      return { content: [{ type: "text", text: "Not authorized" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("funnels").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { funnel: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nzeqkgfeixknufqyrbjf";
var mcp_default = defineMcp({
  name: "flow-map-mcp",
  title: "Flow Map MCP",
  version: "0.1.0",
  instructions: "Tools for the Flow Map conversion-funnel editor. Use list_funnels to list saved funnels and get_funnel to inspect one. Access is restricted to the app owner.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_funnels_default, get_funnel_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
